# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tobiasbu
email: flamenco.bluegrass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Design and Video Games from tobi.
author: Tobias B. Ulrich

#comentar isso quando testar local
baseurl: "" # the subpath of your site, e.g. /blog


url: "https://tobiasbu.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: tobiasbu
disqus_username: tobiasbu
encoding: utf-8
#excerpt_separator: "<!--more-->"

#plugins
plugins:
  - jekyll-pseudocode

#plugins_dir: ./_plugins
#plugins_dir: "_plugins/"


permalink: pretty

# Build settings
markdown: kramdown

highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
kramdown:
  input: GFM
  auto_ids: false
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  # syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
   # css_class: 'highlight'
   # span:
   #   line_numbers: false
   # block:
   #   line_numbers: true

collections:
  games:
    output: true
    path: /untitled-space/
    permalink: /portfolio/:path/

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: true
  startings: [html, head, body]

exclude: ['.sass-cache','css/config','deploy.js', LICENSE.md, 'README.md', 'Gemfile','Gemfile.lock', 'node_modules', 'package.json', 'Gruntfile.js', '_plugins']

include:
  - _pages
