# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tobiasbu
email: flamenco.bluegrass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Design and Video Games from tobi.
author: Tobias B. Ulrich

#comentar isso quando testar local
baseurl: "" # the subpath of your site, e.g. /blog
#plugins_dir: ./_plugins

url: "https://tobiasbu.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: tobiasbu
disqus_username: tobiasbu
encoding: utf-8
#excerpt_separator: "<!--more-->"

#plugins
#plugins_dir: ./_plugins
#plugins_dir: "_plugins/"

permalink: pretty

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  auto_ids: false

highlighter: rouge

collections:
  games:
    output: true
    path: /untitled-space/
    permalink: /portfolio/:path/

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: true
  startings: [html, head, body]

exclude: ['.sass-cache','css/config','deploy.js', 'README.md', 'Gemfile','Gemfile.lock', 'node_modules', 'package.json', 'Gruntfile.js', '_plugins']

include:
  - _pages
